import 'dotenv/config';
import connectDB from '../config/db.js';
import Settings from '../models/Settings.js';
import mongoose from 'mongoose';
await connectDB();
const s = await Settings.getSingleton();
console.log('Before:', s.announcement.messages);
s.announcement.messages = s.announcement.messages.filter(m => !/free shipping/i.test(m));
await s.save();
console.log('After: ', s.announcement.messages);
await mongoose.disconnect();
